### PR TITLE
Few changes changes to avoid some compilation errors

### PR DESCRIPTION
**Pull request by garatronic**
Hi devbis,

Thanks for this driver, it works well now for me and does not need framebuffer. Excellent for high resolution little IPS display on small targets.

### CODE REVIEW

**Comment by devbis** [comment]
Thanks, @garatronic for the pull request. 
I tried to compile for STM32 target and found the issue with brackets.
But MP_ERROR_TEXT() is a required macro for the latest micropython/pycopy versions. Also, it compiles well without removing it from the code.

What version of micropython did you compile?

**Comment by garatronic** [comment]
You're welcome. 
I use the tagged v1.12 
I found a bug with the head version, something wrong with the servos that not accept negative angles. 


De: "Ivan Belokobylskiy" <notifications@github.com> 
À: "devbis/st7789_mpy" <st7789_mpy@noreply.github.com> 
Cc: "Garatronic" <github@garatronic.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 25 Juin 2020 00:16:17 
Objet: Re: [devbis/st7789_mpy] Few changes changes to avoid some compilation errors (#13) 





Thanks, [ https://github.com/garatronic | @garatronic ] for the pull request. 
I tried to compile for STM32 target and found the issue with brackets. 
But MP_ERROR_TEXT() is a required macro for the latest micropython/pycopy versions. Also, it compiles well without removing it from the code. 

What version of micropython did you compile?

**Comment by devbis** [comment]
I removed brackets as you provided in the PR, but added a conditional macro to support both HEAD and <=1.12 version.

Can you please provide an example for your board for the readme section? I will add a section about STM32 to the README

**Comment by garatronic** [comment]
Of course, 
I'm a bit in a hurry today. But i'll do before the end of the week. Do you want some pictures of the board. I'm the manufacturer of ;) 
In copy D.Merisse from [ http://www.mchobby.be/ | www.mchobby.be ] who sell and develop on my board. He's also a big contributor of micropython on github: 
[ https://github.com/mchobby/pyboard-driver/tree/master/PYBStick | https://github.com/mchobby/pyboard-driver/tree/master/PYBStick ] 



De: "Ivan Belokobylskiy" <notifications@github.com> 
À: "devbis" <st7789_mpy@noreply.github.com> 
Cc: "Garatronic" <github@garatronic.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 25 Juin 2020 09:24:19 
Objet: Re: [devbis/st7789_mpy] Few changes changes to avoid some compilation errors (#13) 





I removed brackets as you provided in the PR, but added a conditional macro to support both HEAD and <=1.12 version. 

Can you please provide an example for your board for the readme section? I will add a section about STM32 to the README

**Comment by devbis** [comment]
I don't think the picture of the board is required because it is just a module for the display.
It would be great if you provide a working sample code, like it is done for esp devices. Because I'm not familiar with the pin naming for STM32
```
# ESP32

import machine
import st7789
spi = machine.SPI(2, baudrate=40000000, polarity=1, sck=machine.Pin(18), mosi=machine.Pin(23))
display = st7789.ST7789(spi, 240, 240, reset=machine.Pin(4, machine.Pin.OUT), dc=machine.Pin(2, machine.Pin.OUT))
display.init()
```

**Comment by garatronic** [comment]
Okay, so i'll use the micro port naming, universal. 
Quite simple, ports (16 bits) are defined by a letter : A,B,C followed by the number, number of pin of the port. 
# STM32

import machine
import st7789
spi = machine.SPI(2, baudrate=12000000, polarity=1)
display = st7789.ST7789(spi, 135, 240, reset=machine.Pin('B3', machine.Pin.OUT), dc=machine.Pin('B6', machine.Pin.OUT))
display.init() 


De: "Ivan Belokobylskiy" <notifications@github.com> 
À: "devbis" <st7789_mpy@noreply.github.com> 
Cc: "Garatronic" <github@garatronic.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 25 Juin 2020 10:59:36 
Objet: Re: [devbis/st7789_mpy] Few changes changes to avoid some compilation errors (#13) 





I don't think the picture of the board is required because it is just a module for the display. 
It would be great if you provide a working sample code, like it is done for esp devices. Because I'm not familiar with the pin naming for STM32 
# ESP32

import machine
import st7789
spi = machine.SPI(2, baudrate=40000000, polarity=1, sck=machine.Pin(18), mosi=machine.Pin(23))
display = st7789.ST7789(spi, 240, 240, reset=machine.Pin(4, machine.Pin.OUT), dc=machine.Pin(2, machine.Pin.OUT))
display.init()

**Comment by devbis** [comment]
Thanks for the info. I added a note about stm32 to the readme. 
Closing the task.

**Pull request closed without merging**
